### ISSUE TITLE
Hidden dialog has some padding

### ISSUE THREAD

**Issue by MagicNachoMan** [vanpra/compose-material-dialogs#102]
I've noticed that when a dialog isn't shown, it's still causing some padding in the location where it resides. When I remove the dialog.build statement from my composable the hidden padding disappears. 

It seems to be about 4.dp.

With dialog included in composable but hidden...
![image](https://user-images.githubusercontent.com/23099401/128247652-54543c37-a780-4006-add5-5a0bf5733608.png)

``
    val dialog = remember { MaterialDialog() }

    dialog.build(
        buttons = {
            negativeButton("Cancel")
        }
    ) {
        title(label)
        listItems(
            list = options,
            closeOnClick = true,
            onClick = {selected,_ -> onSelectionChange(selected) }
        )
    }

    Column(
        modifier = modifier.clickable(
            enabled = true,
            onClick = {
                dialog.show()
            }
        ),
    ){
        item()
    }
``

With dialog excluded from composable...

![image](https://user-images.githubusercontent.com/23099401/128248018-faa07ed6-722e-4096-959b-0312f311d169.png)

``
    val dialog = remember { MaterialDialog() }

    /*dialog.build(
        buttons = {
            negativeButton("Cancel")
        }
    ) {
        title(label)
        listItems(
            list = options,
            closeOnClick = true,
            onClick = {selected,_ -> onSelectionChange(selected) }
        )
    }*/

    Column(
        modifier = modifier.clickable(
            enabled = true,
            onClick = {
                //dialog.show()
            }
        ),
    ){
        item()
    }
``

Is this something I'm perhaps doing wrong? Is there any way to prevent a hidden dialog from taking up screen real estate?

I'm using jetpack compose version 1.0.0 and compose material dialogs version '0.5.1'.

Many thanks!

**Comment by vanpra** [comment]
Thanks for letting me know about this bug. I haven't had a chance to check but this may be fixed in the latest 0.6.0 release as I have restructured the core dialog structure. Please let me know if this is still an issue and I will take a closer look.
