### ISSUE TITLE
Datepicker min date stuck to 1922

### ISSUE THREAD

**Issue by VincentJouanne** [vanpra/compose-material-dialogs#105]
Hey guys, thanks a lot for this awesome library, it helps us a lot :) 

I was wondering if we could select a year prior to 1922 because when I set a min date to 1900, the year range is still 1922-2121.

Is there a way to increase it ? 

Thanks a lot !

**Comment by vanpra** [comment]
I don't seem to be able to reproduce the issue. Could you provide the code you're using to build the dialog?
