### ISSUE TITLE
I am getting crash every time with the datepicker

### ISSUE THREAD

**Issue by Shashank02051997** [vanpra/compose-material-dialogs#112]
```
No static method AnimatedVisibility(ZLandroidx/compose/ui/Modifier;Landroidx/compose/animation/EnterTransition;Landroidx/compose/animation/ExitTransition;Lkotlin/jvm/functions/Function3;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/animation/AnimatedVisibilityKt; or its super classes (declaration of 'androidx.compose.animation.AnimatedVisibilityKt' appears in /data/app/com.mirus.orpheuspatientapp.androidApp-uddfwQzqociDqoGlch52bg==/base.apk)
        at com.vanpra.composematerialdialogs.datetime.date.DatePickerKt$DatePickerImpl$1$1.invoke(DatePicker.kt:129)
        at com.vanpra.composematerialdialogs.datetime.date.DatePickerKt$DatePickerImpl$1$1.invoke(DatePicker.kt:117)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:135)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at com.google.accompanist.pager.Pager.Pager-_-WMjBM(Pager.kt:309)
```

**Comment by skolson** [comment]
Seeing the same using compose 1.1.0-alph04

**Comment by skolson** [comment]
Sure enuff, default animation library in use was 1.0.x even though I was using 1.1.0-alpha04. During research I saw that alpha05 is out, which requires kotlin 1.5.31. So changed to both of those and added this to the main kotlin sourceset in the android module:
```
runtimeOnly(androidx.compose.animation:animation:1.1.0-alpha05)
```

This changed the exception when using DatePicker to this:
```
java.lang.NoSuchMethodError: No static method slideInVertically$default...
```
So now I'm looking into where that comes from...

**Comment by skolson** [comment]
Something is still pulling in 1.0.1 of the animations.  This is the only compose library doing this, all the others are just using 1.1.0-alpha05 as desired.  Here's the relevant snip from the External Libraries display for my project:
![image](https://user-images.githubusercontent.com/19804620/136087874-3919b10c-3f37-4867-ac02-ec839b762537.png)

None of my code is explicitly using animations, so this animation 1.0.1 dependency is either coming from date picker or from something within compose.  I'm going to mess with dependencies in gradle to see if I can stop this and force it to only use 1.1.0-alpha05. WIll post again if I find a fix.

**Comment by skolson** [comment]
The 1.0.1 stuff is fixed by changing the gradle entry for animation to "implementation".
```
implementation(androidx.compose.animation:animation:1.1.0-alpha05)
```
But the same error remains when attempting to use date picker even after the 1.0.1 stuff is gone:
```
    java.lang.NoSuchMethodError: No static method slideInVertically$default(Lkotlin/jvm/functions/Function1;Landroidx/compose/animation/core/FiniteAnimationSpec;ILjava/lang/Object;)Landroidx/compose/animation/EnterTransition; in class Landroidx/compose/animation/EnterExitTransitionKt; or its super classes (declaration of 'androidx.compose.animation.EnterExitTransitionKt' appears in /data/app/~~FUPuM9ytG9LZPiGG-y05eg==/com.oldguy.monay-jCFG478Y2cpB30Eod5buJw==/base.apk)
        at com.vanpra.composematerialdialogs.datetime.date.DatePickerKt$DatePickerImpl$1$1.invoke(DatePicker.kt:134)
        ...
```

Still looking...

**Comment by skolson** [comment]
Ok, here's the problem - the method signatures for both slideInVertically and slideOutVertically have changed.  Here's slideInVertically now:
```
fun slideInVertically(
    animationSpec: FiniteAnimationSpec<IntOffset> =
        spring(
            stiffness = Spring.StiffnessMediumLow,
            visibilityThreshold = IntOffset.VisibilityThreshold
        ),
    initialOffsetY: (fullHeight: Int) -> Int = { -it / 2 },
): EnterTransition =
```
Line 134 in date picker is this:
```
enter = slideInVertically({ -it }),
```
and needs to be (at least) this:
```
enter = slideInVertically(initialOffsetY = { -it }),
```
Assuming of course the default animationSpec (now the first argument) is ok.  So I'm stuck for now.
