### ISSUE TITLE
DatePicker: Unable to define colour/style for Month header and Days of Week header 

### ISSUE THREAD

**Issue by pauldavies83** [vanpra/compose-material-dialogs#124]
The elements in this screenshot do not appear to have parameters in to allow their colours to be defined.

![image](https://user-images.githubusercontent.com/6160174/145466183-4938fd2b-442e-473c-82fc-eef9726d6f49.png)

**Comment by Pantsoffski** [comment]
I have also problem with that...

**Comment by JensRoggeband** [comment]
Would be cool to have this option

**Comment by vanpra** [comment]
Thanks for the request. This has been added in version 0.7.0.
