### ISSUE TITLE
How do I change the surface color of the dialog itself?

### ISSUE THREAD

**Issue by KotlinWay** [vanpra/compose-material-dialogs#125]
![Снимок экрана 2021-12-22 в 18 18 43](https://user-images.githubusercontent.com/51969403/147084967-ba910610-e427-4020-9ade-c482dd53f256.png)
Hello. How can I change the dialog color to fully customize the widget? I want to change the white color.

**Comment by vanpra** [comment]
You should be able to do this by making use of the `backgroundColor` of the `MaterialDialog` function
