### ISSUE TITLE
Navigation buttons not visible for DateTimePicker

### ISSUE THREAD

**Issue by Namnodorel** [vanpra/compose-material-dialogs#13]
The "Cancel", "Next", "OK" buttons aren't visible for me when using the datetimepicker (but are with the datepicker!).

I have a pretty small screen, so my guess is that they are pushed out of view by the large header at the top. I think it would generally be a good idea to make dialogs scrollable in case the content overflows.

**Comment by vanpra** [comment]
I've made the dialog scrollable but I wasn't able to test it out on a small. If you have time could you test the dialog in the sample app and let me know if it's fixed. If not I'll try and test it out later today.

**Comment by Namnodorel** [comment]
I'll happily test it, but I'll only get the chance tomorrow.

**Comment by Namnodorel** [comment]
Unfortunately, I couldn't build the new commit myself because I'm already using the newer Kotlin 1.4 RC plugin, and [the JitPack build failed](https://jitpack.io/com/github/vanpra/compose-material-dialogs/main-9cbc0c7799-1/build.log). Could you maybe upload the sample app APK somewhere?

**Comment by vanpra** [comment]
Here's the apk: https://github.com/vanpra/compose-material-dialogs/releases/tag/0.1.6-beta

**Comment by Namnodorel** [comment]
It works in that the navigation buttons are no longer obscured - however
- when scrolling down, the "page indicator" circles get partially obscured
- you can scroll down on the date page, but not up again on the clock page, because the clock "swallows" the swipe gesture
I had also thought more along the lines of making the whole dialog scrollable, instead of a smaller view within. I think that'd be a simple solution for both issues.

**Comment by vanpra** [comment]
I've updated the apk in the above release. I've made everything in the dialog scrollable except for the buttons and also made it so that the page is scrolled to the top when switching from the date section to the time section. I've done some testing and it seems like this is probably the best solution for small devices but if you have any suggestions let me know.

**Comment by Namnodorel** [comment]
The smooth scrolling to the top seems like a good idea :D I have a question, though: Why make it a scrollable within a scrollable? Wouldn't the top level scrollable suffice?

**Comment by vanpra** [comment]
My bad. I thought I removed the inner scrollable but I must have forgotten. I've removed it now, so if everything works well I'll make a new release.

**Comment by Namnodorel** [comment]
Sorry for the delay. Did you update the release again? Installation fails for me without error or exception :/

**Comment by vanpra** [comment]
I haven't updated it yet as I'm holding off till I migrate to dev16. This will probably be in the next couple on days as soon as one of the libraries I'm using also updates to dev16.

**Comment by Namnodorel** [comment]
Yes, this works perfectly ^^ Thanks a lot!
