### ISSUE TITLE
Losing input focus when validity changes

### ISSUE THREAD

**Issue by paumove** [vanpra/compose-material-dialogs#132]
When using a method for "isTextValid", every time the validity of the input changes, the focus on the input element is lost.

**To Reproduce**
```
MaterialDialog(
        dialogState = dialogState
    ) {
        input(
            label = "Port number",
            prefill = "1",
            isTextValid = {input: String -> input.toIntOrNull() in 1..65535 },
            errorMessage = "Must be between 1 and 65535",
        )
    }
```

**Expected behaviour**
The focus would not be expected to be removed from the input even if its validity changes.

**Comment by vanpra** [comment]
Thanks for reporting this bug. This should now be fixed in 0.7.0.
