### ISSUE TITLE
Remove `material-icons-extended` as a dependency of `compose-material-dialogs:core` and others

### ISSUE THREAD

**Issue by yankeppey** [vanpra/compose-material-dialogs#153]
**Describe the bug**
After I added `compose-material-dialogs:core` to my project, 20 mb was added to the final apk size. It seems it brought the whole material-icons-extended library with it:
```
 +--- io.github.vanpra.compose-material-dialogs:core:0.7.0
|    |    |    +--- androidx.core:core-ktx:1.7.0 (*)
|    |    |    +--- androidx.compose.ui:ui:1.1.1 (*)
|    |    |    +--- androidx.compose.material:material:1.1.1 (*)
|    |    |    +--- androidx.compose.material:material-icons-extended:1.1.1
|    |    |    |    +--- androidx.compose.material:material-icons-core:1.1.1 (*)
|    |    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.6.10
|    |    |    |    \--- androidx.compose.runtime:runtime:1.1.1 (*)
|    |    |    +--- androidx.compose.animation:animation:1.1.1 (*)
|    |    |    +--- androidx.compose.foundation:foundation-layout:1.1.1 (*)
|    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.10 (*)
```

**Expected behaviour**
I don't expect a library showing dialogs to bring any icons with it, and for sure it should not depend on the extended set of the material icons.

**Suggested solution**

- This seems to be the reason, the same set of dependenies is applied to every library:
https://github.com/vanpra/compose-material-dialogs/blob/main/buildSrc/src/main/kotlin/CommonModulePlugin.kt#L29

The material icons [are used in several places](https://github.com/vanpra/compose-material-dialogs/search?q=icons.), such as: Demos, Tests, and in a couple of places in DatePicker module.
Let's leave the dependency of `material-icons-extended` only for Demos and Tests, and for DatePicker, let's copy-paste the used icons, as suggested in [the docs](https://developer.android.com/reference/kotlin/androidx/compose/material/icons/package-summary):

> Due to the very large size of this library, make sure to use R8/Proguard to strip unused icons if you are including this library as a direct dependency. Alternatively you can make a local copy (by copy and pasting) the icon(s) you wish to keep, or using Android Studio's 'Import vector asset' feature.

**Comment by vanpra** [comment]
Fixed in 0.8.1-rc
