### ISSUE TITLE
Version 0.2.0 can't be resolved

### ISSUE THREAD

**Issue by Namnodorel** [vanpra/compose-material-dialogs#16]
This seems to be a similar problem to #14 - updating to `0.2.0` yields the error

> Could not find com.vanpra.compose-material-dialogs:core:0.2.0.

**Comment by Namnodorel** [comment]
nvm, I noticed that I was missing
````
maven {
    url  "https://dl.bintray.com/vanpra/maven" 
}
````

**Comment by Namnodorel** [comment]
Nvm the nvm, it's broken nonetheless xD

**Comment by vanpra** [comment]
My mistake, I forgot to publish the package to JCenter. Should be working now.
