### ISSUE TITLE
Year Selection Update

### ISSUE THREAD

**Issue by yamilagammeri** [vanpra/compose-material-dialogs#17]
Hi Vanpra,

I was wondering how soon you would be implementing year selection for the date picker?

Kind Regards,
Yamila

**Comment by vanpra** [comment]
I'll try and look into this later today. Hopefully should be implemented in the next couple of days

**Comment by yamilagammeri** [comment]
Thanks! Can't wait till it's implemented 😄

**Comment by vanpra** [comment]
I've had a look into this and it seems to be slightly harder to fit in than I expected. It will probably take a couple more week to be implemented as I want to clean up the code of the date picker before trying to implement this again. This should hopefully be done by the next compose release.

**Comment by Brett-Best** [comment]
@vanpra be great once this is implemented!

**Comment by vanpra** [comment]
Sorry for the delay on this feature. I'm quite busy at the moment and haven't had much time to work on this. From what I've seen so far this feature probably take a while to implement as it requires a partial rewrite of core functionality as this introduces a new scroller/lazylist into the dialog which currently crashes the app. I'll try and get to this as soon as possible but if someone would be willing to help me out on this I would be more than happy to have a discussion with them on what needs to be done.

**Comment by vanpra** [comment]
This has now been implemented in the date picker dialog but it can be a bit buggy some times so feel free to create an issue if you experience any bugs.
