### ISSUE TITLE
Manifest error

### ISSUE THREAD

**Issue by ALefaux** [vanpra/compose-material-dialogs#20]
I've got this error when I try to use your library : 
`AAPT: error: resource style/Theme.Composematerialdialogs (aka ...:style/Theme.Composematerialdialogs) not found.`

Could you remove **Application** tag in Core's manifest please ?

**Comment by vanpra** [comment]
I don't seem to be getting this error on my end. Could you please provide your compose version and the code you're using to create the dialog?

**Comment by ALefaux** [comment]
Your library version used: 0.2.5
Compose version used : 1.0.0-alpha06

How I use your library: 
`val dialog = MaterialDialog()
    dialog.build {
        listItems(list = items, onClick = { index, item ->
            selectedText.value = item
        })
    }
    Button({
        dialog.show()
    }) {
        ...
    }`

This is my AndroidManifest: 
`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="fr.alefaux.pollochon">

    <uses-permission android:name="android.permission.INTERNET"/>

    <application
        android:name=".PollochonApp"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true">
        <activity android:name=".views.splashscreen.SplashscreenActivity"
            android:theme="@style/SplashscreenTheme">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name=".views.home.HomeActivity"
            android:theme="@style/HomeTheme"/>
    </application>

</manifest>`

This is the AndroidManifest generated in build folder: 
`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="fr.alefaux.pollochon"
    android:versionCode="1"
    android:versionName="1.0" >

    <uses-sdk
        android:minSdkVersion="23"
        android:targetSdkVersion="30" />

    <uses-permission android:name="android.permission.INTERNET" />

    <application
        android:name="fr.alefaux.pollochon.PollochonApp"
        android:allowBackup="true"
        android:appComponentFactory="androidx.core.app.CoreComponentFactory"
        android:debuggable="true"
        android:extractNativeLibs="false"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:testOnly="true"
        android:theme="@style/Theme.Composematerialdialogs" >
        <activity
            android:name="fr.alefaux.pollochon.views.splashscreen.SplashscreenActivity"
            android:theme="@style/SplashscreenTheme" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name="fr.alefaux.pollochon.views.home.HomeActivity"
            android:theme="@style/HomeTheme" />
        <activity
            android:name="androidx.ui.tooling.preview.PreviewActivity"
            android:exported="true"
            android:theme="@android:style/Theme.Material.Light.NoActionBar" />

        <provider
            android:name="androidx.lifecycle.ProcessLifecycleOwnerInitializer"
            android:authorities="fr.alefaux.pollochon.lifecycle-process"
            android:exported="false"
            android:multiprocess="true" />
    </application>

</manifest>`
Which contains your theme.

**Comment by vanpra** [comment]
Thanks, this was a mistake on my part when I was trying experiment with some things a couple of weeks ago. I have now removed the tag from the manifest and will release a new version later today with this fix along with an update to the latest version of compose.

**Comment by vanpra** [comment]
I've just published the new version (0.2.6) which should fix this issue. Let me know if this is not the case and I'll look into it as soon as possible.
