### ISSUE TITLE
Auto dismiss has no effect

### ISSUE THREAD

**Issue by SaidAlSouti** [vanpra/compose-material-dialogs#22]
Setting autoDismiss to false or true appears to have no effect.
`val dialog = MaterialDialog(autoDismiss = false)`

**Comment by vanpra** [comment]
This seems to be working for me when I test it on my device as the dialog doesn't get hidden on positive or negative button press when autoDismiss is set to false. Could you let me know what you were doing to test this feature so that I can try and replicate the problem.

**Comment by SaidAlSouti** [comment]
I am really grateful for your awesome library. It seems there is tiny bug, which i fixed in my app:
`
/**
     * @brief Builds a dialog with the given content
     * @param content the body of the dialog
     */
    @Composable
    fun build(
        backgroundColor: Color = MaterialTheme.colors.background,
        content: @Composable MaterialDialog.() -> Unit
    ) {
        if (showing.value) {
            ThemedDialog(onCloseRequest = {
                **if(autoDismiss) hide()**
            }) {
                Column(
                    modifier =
                        Modifier.fillMaxWidth()
                            .background(backgroundColor, shape = MaterialTheme.shapes.medium)
                            .clip(MaterialTheme.shapes.medium)
                ) {
                    this@MaterialDialog.content()
                }
            }
        }
    }
`

You need to check if autoDismiss is true before calling hide(). Please fix this in your repo.
I know that I should ask for pull request, and I will do it when I got time. Thanks a lot.

**Comment by vanpra** [comment]
Ah, I see. This wasn't really the intended use of the `autoDismiss` parameter as it only applies to the buttons in the dialog being clicked so that you could modify the content of the dialog when the positive or negative button was clicked instead of it being hidden. If you could give me some info on your use case for this I'd be more than happy to add this functionality but I don't think that a dialog which cannot be closed should be shown to the user, however, I can see the use of a `onCloseRequest` callback instead.

**Comment by SaidAlSouti** [comment]
I see.

Sometimes you want persistent dialog where the user has to confirm or cancel.

Thanks again for your library.

**Comment by vanpra** [comment]
I've looked into this and I think the best way to implement this would be add a `onCloseRequest` parameter to the `MaterialDialog` class which defaults to `{ hide() }`. So if you don't want it to hid you can just set this parameter to `{}` and also gives some flexibility if someone wants to make the `onCloseRequest` call to do something else as well. This should be a pretty quick fix so I'll probably release a new version with this feature some time later today or tomorrow.

**Comment by SaidAlSouti** [comment]
Appreciated
Fixed
Thanks @vanpra
