### ISSUE TITLE
Android 8 required? (API 26)

### ISSUE THREAD

**Issue by max-grossmann** [vanpra/compose-material-dialogs#23]
Hey vanpra,

i'm new to jetpack compose and played a bit with your library. It seemed that Android 8 is the minimum supported version isn'it? At least for the date picker i'm unable to access the LocalDate object in versions below ("
Call requires API level 26 (current min is 21): java.time.LocalDate#format")

Maybe It would be helpful, if this would be clairified in the README.
Or you can point out a workaround.

My problematic code:
```kotlin
val textState = remember { mutableStateOf(TextFieldValue()) }

dialog.build {
    datepicker { date ->
        val formattedDate = date.format(
            DateTimeFormatter.ofPattern("dd.MM.yyyy")
        )
        textState.value = TextFieldValue(formattedDate)
    }
}
```

Thanks for this great library!

Max

**Comment by vanpra** [comment]
Hi Max,
I've added a prerequisite note to the top of the date time picker documentation which should solve your issue. If not, let me know and I'll take another look

**Comment by MaaxGr** [comment]
Hi vanpra,
thx for this fast response. I will try that out later! Also didn't know that with the desugaring. Really interesting. :)

**Comment by max-grossmann** [comment]
Works! Thank you
