### ISSUE TITLE
Input dialog

### ISSUE THREAD

**Issue by JakubDzama2** [vanpra/compose-material-dialogs#25]
allowEmpty = false ... does not work correctly - when empty, positive button is enabled, and after some text is added, positive button becomes disabled

Please, add functionality to pass a KeyboardOptions to the input dialog. Thanks!

**Comment by vanpra** [comment]
I've added the keyboardOptions functionality to the input component and also removed the allowEmpty parameter in favour of the isTextValid parameter where you can define your own input validation which should now work when given { it.isNotEmpty() }. These changes should be available in the latest version 0.2.11 so let me know if you still face any issues.

**Comment by JakubDzama2** [comment]
Thank you very much!

št 14. 1. 2021 o 22:00 Pranav Maganti <notifications@github.com> napísal(a):
