### ISSUE TITLE
Please update to compose alpha12

### ISSUE THREAD

**Issue by ln-12** [vanpra/compose-material-dialogs#27]
After updating to the lastest compose release `1.0.0-alpha12`, I get errors like `java.lang.NoSuchMethodError: No virtual method startRestartGroup(ILjava/lang/String;)V in class Landroidx/compose/runtime/Composer; or its super classes ...`. I think it's caused by the incompatibility between different alpha versions.

**Comment by vanpra** [comment]
Thanks, for letting me know. Check #26 for more info about this issue.
