### ISSUE TITLE
Unable to get working

### ISSUE THREAD

**Issue by gabriel403** [vanpra/compose-material-dialogs#34]
I have created a composeable function that observes a state flow property, when true it passes an object into another composeable funtion and then populates the datepicker with a property of the object, it then calls show on the dialog. But it never seems to show the dialog

```
@Composable
fun MainScreen(viewModel: MyViewModel) {
	val currentItem by viewModel.currentItem.collectAsState()
	val showEditDialog by viewModel.showEditDialog.collectAsState()
	Timber.i("Show Edit Dialog: %b", showEditDialog)
	Timber.i("Current Item: %s", currentItem?.id)
	if (showEditDialog && currentItem !== null) {
		DatePicker(item = currentItem!!)
	}
}


@Composable
fun DatePicker(item: MyItem) {
	Timber.i("Showing DatePicker")
	val dialog = MaterialDialog()
	dialog.build {
		datepicker(item.updateDate) { date ->
			// Do stuff with java.time.LocalDate object which is passed in
			Timber.i("Date picked: %s", date.toString())
		}
	}
	dialog.show()
}
```
and the log output is
```
2021-03-13 19:30:31.968 5332-5332/co.g403.myapp I/ScreensKt: Show Edit Dialog: true
2021-03-13 19:30:31.969 5332-5332/co.g403.myapp I/ScreensKt: Current Item: 3c86a781-60f6-4801-9cf4-f132a114d9e3
2021-03-13 19:30:31.984 5332-5332/co.g403.myapp I/ScreensKt: Showing DatePicker
```

**Comment by gabriel403** [comment]
It works if I switch the order, presumably because the Composable doesn't get added otherwise?
```
	val dialog = MaterialDialog()
	dialog.show()
	dialog.build {
		datepicker(loaf.updateDate) { date ->
			// Do stuff with java.time.LocalDate object which is passed in
			Timber.i("Date picked: %s", date.toString())
		}
	}
```

**Comment by vanpra** [comment]
Thanks for creating this issue. The example you've given doesn't use the library in the correct way, which may be partly due to the way I've structured the the example in the documentation. The `MaterialDialog` object should ideally be created and built in the top layer of your UI and then passed to other functions which call `dialog.show()` on the object. This means that you don't need the showEditDialog as this is handled by the internal logic and instead you should call `dialog.show()` at the point you want to show the dialog.

**Comment by gabriel403** [comment]
> Thanks for creating this issue. The example you've given doesn't use the library in the correct way, which may be partly due to the way I've structured the the example in the documentation. The `MaterialDialog` object should ideally be created and built in the top layer of your UI and then passed to other functions which call `dialog.show()` on the object. This means that you don't need the showEditDialog as this is handled by the internal logic and instead you should call `dialog.show()` at the point you want to show the dialog.

But how would you update the content when you have multiple items that could have their date updated? I wouldn't want to create a different dialog for each item

**Comment by vanpra** [comment]
For this example I believe the following should work:

```
@Composable
fun MainScreen(viewModel: MyViewModel) {
	val currentItem by viewModel.currentItem.collectAsState()
	Timber.i("Current Item: %s", currentItem?.id)
        DatePicker(item = currentItem!!)
}


@Composable
fun DatePicker(item: MyItem) {
	val dialog = remember { MaterialDialog() }
        DisposableEffect(item) {
            dialog.show()
            onDispose { dialog.hide() } 
       }


	Timber.i("Showing DatePicker")
	dialog.build {
		datepicker(item.updateDate) { date ->
			// Do stuff with java.time.LocalDate object which is passed in
			Timber.i("Date picked: %s", date.toString())
		}
	}
}
```

I've just added a Disposable effect which shows and hides the dialog when there is a change to the item and datepicker should automatically re-compose if there is a change to the `initialDate` given. I haven't had a change to test this code out locally at the moment but if you have any problems let me know and I'll try and take a look later today.
