### ISSUE TITLE
Multiple Color chooser issues

### ISSUE THREAD

**Issue by Jahor** [vanpra/compose-material-dialogs#36]
There are multiple issues with the color chooser:
1) if waitForPositiveButton is true it calls onColorSelected multiple times - for every time it recomposed function and with different colors.
2) it adds RGB picker to layout even if not enabled. That calls onColorSelected with white color, as slider's onValueChanged triggers and sets color to white (see pt. 4).
3) initialSelection does not affect UI of picker or RGB selector
4) Sliders in RGB mode snap back to max (0xFF)
5) Current code does not handle single-level color selection correctly. 
if waitForPositiveButton is true without subcolors it does not set selectedColor.value
If waitForPositiveButton is false with subcolors it incorrectly calls onColorSelected before showing sub colors (may be OK).

I would suggest updating examples to actually demo onColorSelected callback/waitForPositiveButton and displaying selected color.

**Comment by vanpra** [comment]
Thanks for the issue. I've already merged in the changes which fix this bug and l'll try to get a new release out sometime over the weekend. I've also been experimenting with automated UI tests and should have some basic ones soon, which should hopefully mean I can catch these bugs earlier.
