### ISSUE TITLE
Add customisation for title and buttons in date and time picker dialogs

### ISSUE THREAD

**Issue by deepakgahlot98** [vanpra/compose-material-dialogs#37]
Is it possible we can offer the customization to date and time dialog. For example the title color of the dialog and buttons(text, color)

**Comment by vanpra** [comment]
Thanks for the feature suggestion. This has been implemented in 0.4.0.

**Comment by damiancioo** [comment]
This is not working as in 0.4.0 in TimePickerTitle there is `text` value is hardcoded to "SELECT TIME"
