### ISSUE TITLE
Currently hosted on about to sunset bintray 

### ISSUE THREAD

**Issue by rahulsainani** [vanpra/compose-material-dialogs#46]
Since [bintray is sunsetting on 1st May 2021](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), would be a good idea to move this dependency to maven central perhaps.

**Comment by vanpra** [comment]
Thanks for the heads up. I've already been changing stuff to move the dependency to maven central so the next release should be going out on there.

**Comment by rahulsainani** [comment]
Thanks for the quick response, should we keep the issue open till the next release is out? so no one else creates the same issue again.

**Comment by vanpra** [comment]
Yep, my bad. Didn't mean to close it.

**Comment by rahulsainani** [comment]
Closing this as 0.3.3 is now on maven central! Thanks for updating it!
