### ISSUE TITLE
Allow using IME Action as positive button

### ISSUE THREAD

**Issue by Namnodorel** [vanpra/compose-material-dialogs#47]
Right now, the user always has to press an in-dialog button to complete the dialog. However, in some dialogs where the only interact-able element is an `input()` element, it would be more convenient to just use the IME action to close the dialog.

**Comment by vanpra** [comment]
This has been added and will be available in the next release.

**Comment by Namnodorel** [comment]
Thank you very much! :D I especially appreciate the quick reaction, that's much better than a lot of bigger projects.
