### ISSUE TITLE
Start accepting T types

### ISSUE THREAD

**Issue by zunjae** [vanpra/compose-material-dialogs#52]
I'll keep it short. Version:  implementation "io.github.vanpra.compose-material-dialogs:core:0.3.3"

It's not possible to pass a List of T (or simply a "Collection") into methods such as `listItems(list = `. This breaks a lot of flexibility, and looking at the source code there is no reason you're accepting a List of Strings (other than wanting to copy Afollestad)

Please consider accepting T/Collection types. To render text on screen you can call its toString().

---

Right now I need to map my existing List of custom models into a List<String>, then get the original object back from the list of indices...

---

For what it's worth, internally you're calling `inline fun <T> LazyListScope.itemsIndexed(items: List<T>` which also accepts T type

**Comment by vanpra** [comment]
There are 2 overloaded implementations of `listItems`. The first one which you mentioned is the one which takes a `String` type and displays a simple text list but the other one takes a generic `List<T>` and then allows you to define a custom item composable which can be seen [here](https://github.com/vanpra/compose-material-dialogs/blob/main/core/src/main/java/com/vanpra/composematerialdialogs/MaterialDialogLists.kt#L84).

**Comment by zunjae** [comment]
Could you tell me what I am doing wrong?

    listItems(list = listOf("Hello", "World"), onClick = { _, item ->
      
    })

This works, displays a dialog with entries

    listItems(list = listOf("Hello", "World"), item= { _, item ->
      
    })
    
Doesn't work, only shows a dialog with the title

**Comment by zunjae** [comment]
listItemsMultiChoice has the same issue. I made an extension method like this:

```
@Composable
fun <T> MaterialDialog.listItemsMultiChoice2(
  list: List<T>,
  disabledIndices: List<Int> = listOf(),
  initialSelection: List<Int> = listOf(),
  waitForPositiveButton: Boolean = true,
  onCheckedChange: (indices: List<Int>) -> Unit = {}
) {
  var selectedItems by remember { mutableStateOf(initialSelection.toMutableList()) }

  val callbackIndex = rememberSaveable {
    val index = callbackCounter.getAndIncrement()

    if (waitForPositiveButton) {
      callbacks.add(index) { onCheckedChange(selectedItems) }
    } else {
      callbacks.add(index) { }
    }

    index
  }

  DisposableEffect(Unit) {
    onDispose {
      callbacks[callbackIndex] = {}
    }
  }

  val onChecked = { index: Int ->
    if (index !in disabledIndices) {
      val newSelectedItems = selectedItems.toMutableList()
      if (index in selectedItems) {
        newSelectedItems.remove(index)
      } else {
        newSelectedItems.add(index)
      }
      selectedItems = newSelectedItems
      if (!waitForPositiveButton) {
        onCheckedChange(selectedItems)
      }
    }
  }

  val isEnabled = { index: Int -> index !in disabledIndices }

  listItems(
    list = list,
    onClick = { index, _ -> onChecked(index) },
    isEnabled = isEnabled,
    closeOnClick = false
  ) { index, item ->
    val enabled = remember(disabledIndices) { index !in disabledIndices }
    val selected = index in selectedItems

    Row(
      Modifier
        .fillMaxWidth()
        .height(48.dp),
      verticalAlignment = Alignment.CenterVertically
    ) {
      Checkbox(checked = selected, onCheckedChange = { onChecked(index) }, enabled = enabled)
      Spacer(
        modifier = Modifier
          .fillMaxHeight()
          .width(32.dp)
      )
      Text(
        item.toString(),
        color = if (enabled) {
          MaterialTheme.colors.onSurface
        } else {
          MaterialTheme.colors.onSurface.copy(ContentAlpha.disabled)
        },
        style = MaterialTheme.typography.body1
      )
    }
  }
}
```

Would appreciate it if this made it to the actual library

**Comment by vanpra** [comment]
As in the previous comment there are 2 different overloaded versions of `listItems`. In the first example you give you do not supply a composable `item` and hence it defaults to the implementation of making a basic list view with the strings provided. In the second example you have passed in an empty composable as the item parameter and hence your getting an empty dialog.

**Comment by vanpra** [comment]
For the `listItemsMultiChoice` I think its better to leave it as a List of strings as the input as this is more explicit about what/how the dialog uses the list instead of calling `toString` on the items.

**Comment by zunjae** [comment]
It's okay I made my own extension methods and it works now!
