### ISSUE TITLE
Option for the first day of the week

### ISSUE THREAD

**Issue by Namnodorel** [vanpra/compose-material-dialogs#54]
I've had testers request an option to pick which day is supposed to be the first day of the week in the datepicker. Since that's currently not possible afaik, I would like to request making it an (optional) argument for the date picker.

**Comment by vanpra** [comment]
Sorry, not quite sure I fully understand the request. Would this just be an argument in the datepicker which take in a day such as Monday, Tuesday, etc. and then set up the date picker to show that day's column to be the first on in the calendar view?

**Comment by Namnodorel** [comment]
Yes, precisely.

**Comment by vanpra** [comment]
Doesn't seem like there's any way to do this from the locale so I'll just make it a parameter for now. I'm currently working on a couple of other features on the date picker so I'll try and get this implemented after those are done which should be soon.

**Comment by kalinjul** [comment]
Here's my PR to make first day of week locale based:
https://github.com/vanpra/compose-material-dialogs/pull/135
