### ISSUE TITLE
Dialog for Date and time do not show OK and CANCEL buttons

### ISSUE THREAD

**Issue by deepakgahlot98** [vanpra/compose-material-dialogs#57]
In the v0.3.3 version of the library, I do not show the negative and positive buttons for the dialog.
Attached is the screenshot for your reference 
<img width="397" alt="Screenshot 2021-04-21 at 8 18 16 AM" src="https://user-images.githubusercontent.com/13279310/115489955-bb7a5b00-a27a-11eb-9ae0-1e7c67ad2a83.png">

**Comment by vanpra** [comment]
Have you added the buttons to the dialog when building? Here's an example: 
```
dialog.build {
    datepicker()
    buttons {
        positiveButton("Ok") 
        negativeButton("Cancel")
    }
}
```
