### ISSUE TITLE
Date Picker Dialog bug

### ISSUE THREAD

**Issue by newAndroidDeveloper** [vanpra/compose-material-dialogs#61]
- Thank you for making this library for jetpack compose really appreciate it❤
- there is a bug with the date picker dialog, after swiping to a different month the date selection focus round dot does not appear when you select a date
- attached a view for reference
- Am wondering what would be the fix for that? Thank you

https://user-images.githubusercontent.com/83723306/117185961-637a4300-ada8-11eb-89e8-1400cb1fbdb5.mp4

**Comment by vanpra** [comment]
Thanks for the bug report. I'll put out a fix for this in the new release later today.

**Comment by newAndroidDeveloper** [comment]
great Thank you so much

**Comment by vanpra** [comment]
Fixed in 0.4.0
