### ISSUE TITLE
Datepicker quirk

### ISSUE THREAD

**Issue by MagicNachoMan** [vanpra/compose-material-dialogs#65]
Hi, this library is great, thank you for creating it. I'm quite new to development so don't know if I'm going through the right channels to raise this, but I've noticed a little issue with the datepicker where if you select a date in a new calendar page it isn't highlighting the number. I'm not sure if it's a bug with my implementation or not. The problem is present in my emulator and on my phone.

The image below shows that I have selected 03/06/2021 but you can see the circle isn't around the date.
![image](https://user-images.githubusercontent.com/23099401/117358225-cc97ae80-aead-11eb-88be-45b6db7c2ac3.png)

If I go back to the current month.
![image](https://user-images.githubusercontent.com/23099401/117358382-ff41a700-aead-11eb-9c73-4d7bc5fc2c34.png)

**Comment by vanpra** [comment]
Thanks for the issue. This was a bug in the 0.3.4 release but should be fixed in the 0.4.0 release which was put out earlier today.
