### ISSUE TITLE
Add test tags for ui testing

### ISSUE THREAD

**Issue by Riomhchlaraitheoir** [vanpra/compose-material-dialogs#66]
When writing a ui test, it is useful to be able to input data into a form element. Currently it is difficult to input data if the form element uses one of these dialogs as finding various nodes in the dialog is challenging. As it is, it can be done, however not only is it difficult to do, but it's also easily broken if the slightest piece of a dialogs structure changes in an update.

Test tags could offer a solution. E.g.: for the single choice dialog a tag could be added to each choice element ("choice-$index"?). Using tags like this would make it much easier to find nodes of interest

**Comment by vanpra** [comment]
Thanks for creating this issue. I've already added all the testing tags in the `testing` repository and I will release these along with a test-utils dependency which will easily allow you to get and test different dialog components. I'll make a new release once I finish writing the tests for all the dialog components. You can keep track of the progress on #39.

**Comment by Riomhchlaraitheoir** [comment]
Thanks! Look forward to seeing it merged 👍
