### ISSUE TITLE
Auto focus input field

### ISSUE THREAD

**Issue by Tgo1014** [vanpra/compose-material-dialogs#67]
First I would like to thank the author because this library is extremely useful!

My question is if there's a way for auto-focusing the input field so the keyboard show automatically and the user can type right away.

**Comment by vanpra** [comment]
Currently there's no way to do this as far as I'm aware but I'll take a look into it and maybe add some kind of focus manager field to the input dialog.

**Comment by vanpra** [comment]
I've added `focusRequester` and `focusOnShow` parameters to the input component which can be used to focus a text field when it is shown in the 0.4.2 release. You can see an example of the usage of it in the sample app.

**Comment by Tgo1014** [comment]
Thank you @vanpra !
