### ISSUE TITLE
Compose dependencies need update 

### ISSUE THREAD

**Issue by vahidtavana** [vanpra/compose-material-dialogs#70]
Compose has updated to 1.0.0-beta07 breaking this project.
Compose-related dependencies need update as describe here.
https://developer.android.com/jetpack/androidx/releases/compose-compiler#1.0.0-beta07

**Comment by Tgo1014** [comment]
Unfortunately, upgrading compose breaks this lib as per link posted above.
I receive:

>  java.lang.NoSuchMethodError: No interface method startRestartGroup(ILjava/lang/String;)Landroidx/compose/runtime/Composer; in class Landroidx/compose/runtime/Composer; or its super classes

**Comment by vanpra** [comment]
Should be fixed in the new 0.4.1 release
