### ISSUE TITLE
ListItem issue when list count is greater than 8

### ISSUE THREAD

**Issue by vahidtavana** [vanpra/compose-material-dialogs#73]
When using ListItems in dialog, if list count is greater than 8, the 8th item is rendered blank. 

![list](https://user-images.githubusercontent.com/16610496/119417691-c3c22c00-bd39-11eb-9aa2-a75d6da30e34.PNG)

**Comment by MairwunNx** [comment]
The same problem after updating to new version. But I've 5 elements 😂

![Screenshot_1621930451](https://user-images.githubusercontent.com/39625750/119463329-579bf400-bd4a-11eb-8afd-8347693fdf6e.png)

**Comment by MathewSachin** [comment]
I think this issue is related to compose-beta07.
I'm facing the same issue in LazyColumn even when I'm not using this library.

This issue on the compose issue tracker seems related: https://issuetracker.google.com/issues/188855913

**Comment by MairwunNx** [comment]
@MathewSachin thanks for news! So, we must just waiting new version of Jetpack Compose I hope it will fixed in `beta08`.

**Comment by MathewSachin** [comment]
Compose beta-08 did fix this issue.
But, now we have another bigger problem.

LazyColumn/LazyRow layouts don't recompose in some cases.
https://issuetracker.google.com/issues/190077286

Will have to wait around 2 weeks for beta09 and hope this gets fixed by then.

**Comment by vanpra** [comment]
Thanks for letting me know. I'm going to close this issue as this bug is more to do with compose rather than with this library.
