### ISSUE TITLE
Text Clipping/Wrapping when Largest Font size is set in System settings

### ISSUE THREAD

**Issue by Jahor** [vanpra/compose-material-dialogs#75]
First is ":" in Time Dialog. If set to the same font size as numbers (50 Sp) it looks fine. Another option would be a custom baseline-based alignment.
![":" in Time Dialog.](https://user-images.githubusercontent.com/457326/120168221-bf72a300-c252-11eb-8f0c-24b3c02e7dee.png)
Second is (A)RGB sliders. Width of 40 Dp for the field seems enough.
![(A)RGB sliders](https://user-images.githubusercontent.com/457326/120168215-be417600-c252-11eb-9729-0cd157e5d59c.png)

**Comment by vanpra** [comment]
Thanks for letting me know about these issues. I'm a bit busy at the moment so won't be fixing this for the coming release but I will try to get to it asap. In the meantime feel free to submit a PR if you want to.

**Comment by vanpra** [comment]
Should be fixed in 0.5.0 release
