### ISSUE TITLE
Timepicker title might be not visible when there is already title compose

### ISSUE THREAD

**Issue by damiancioo** [vanpra/compose-material-dialogs#80]
For example if user want a bigger font for title, there is a title element, which can be added to MaterialDialog, but then even if title is set to empty string, MaterialDialog is rendering empty space, which might be a lot of waste for smaller devices.

Example:
```
MaterialDialog = MaterialDialog().also {
    it.build {

        title(res = R.string.date_picker_select_time)

        timepicker(
            title = "",
            initialTime = LocalTime.now(),
            onTimeChange = {}
        )

        buttons {
            positiveButton(
                res = android.R.string.ok
            )
            negativeButton(
                res = R.string.cancel_button_title
            )
        }
    }
}
```
![device-2021-06-09-131016](https://user-images.githubusercontent.com/37381435/121344619-43e4b600-c924-11eb-995a-b68e875c57bc.png)

**Comment by vanpra** [comment]
This should be fixed in the 0.4.3 release.
