### ISSUE TITLE
Error when trying to show date picker

### ISSUE THREAD

**Issue by NurseyitTursunkulov** [vanpra/compose-material-dialogs#82]
java.lang.NoSuchMethodError: No interface method startRestartGroup(ILjava/lang/String;)Landroidx/compose/runtime/Composer; in class Landroidx/compose/runtime/Composer; or its super classes (declaration of 'androidx.compose.runtime.Composer' appears in /data/app/com.example.hellocompose-9xgvXuk8s1ao_3F01Tslsg==/base.apk)

This error appears when I want to show a datapicker.

**Comment by vanpra** [comment]
Can you please provide the dialog code which you are using?

**Comment by NurseyitTursunkulov** [comment]
`  val dialog = remember { MaterialDialog() }
    dialog.build {

        datepicker { date ->
            onDateSelected(date.toString())
        }
        buttons {
            positiveButton("Ok")
            negativeButton("Cancel")
        }
    }

> Can you please provide the dialog code which you are using?

`

**Comment by vanpra** [comment]
This doesn't seem to be an issue with the library as I cannot reproduce this issue when testing on multiple devices. Please check that your dependencies are all at their latest versions and try using to the newly released 0.4.3 release along with 1.0.0-beta09.
