### ISSUE TITLE
dialog fills up the screen 

### ISSUE THREAD

**Issue by hyoban** [vanpra/compose-material-dialogs#90]
I copied the two functions DialogAndShowButton and DateTimeDialogDemo to an initial project. Then I tried to display them

```kotlin
@Composable
fun Greeting() {
    Column {
        DateTimeDialogDemo()
    }
}
```

But the dialog box fills the horizontal direction of the screen

![Screenshot_2021-07-03-19-53-33-891](https://user-images.githubusercontent.com/38493346/124353395-e1d45380-dc38-11eb-9e0b-39d78410c17a.jpg)

I ran the sample software of the project and everything is displayed normally. Is there anything I haven’t noticed?

**Comment by hyoban** [comment]
It seems to be caused by the compose version rc01

**Comment by yannickpulver** [comment]
https://github.com/vanpra/compose-material-dialogs/pull/91 This PR should fix the issue
