### ISSUE TITLE
Dialog Padding

### ISSUE THREAD

**Issue by MagicNachoMan** [vanpra/compose-material-dialogs#93]
For some reason I seem to have lost the horizontal padding around my material dialog boxes. I'm pretty sure there was padding there originally in previous material dialog versions. 

Is this customisable or has something changed in how to apply this? I couldn't see how this padding could be customised as part of the dialog builder.

Many thanks!

![image](https://user-images.githubusercontent.com/23099401/126462605-a98999c0-19ee-4d08-a1e9-765379f486d6.png)

**Comment by vanpra** [comment]
Thanks for the bug report. This was probably due to some changes I made to fix the padding of the dialog on smaller screens. This is already fixed in the 0.5.0 branch which I will release as soon as possible.

**Comment by vanpra** [comment]
Fixed in 0.5.0 release
