### ISSUE TITLE
Cannot import datetimepicker

### ISSUE THREAD

**Issue by wakaztahir** [vanpra/compose-material-dialogs#98]
![Screenshot 2021-07-30 091000](https://user-images.githubusercontent.com/42442700/127598930-4ba6afe6-e4c6-4cc3-b7aa-8de2efd563bd.png)

**Comment by vanpra** [comment]
Hey, I have removed the date time picker from the library due to the fact that the date dialog and time dialog have different styles which doesn't make the transition between them very nice. The implementation was also very hacky which made it quite unmaintainable and time consuming.
