### ISSUE TITLE
Cannot import `buttons` extensions

### ISSUE THREAD

**Issue by Tgo1014** [vanpra/compose-material-dialogs#99]
With version `0.5.1` most of the import issues were solved but buttons still not importable.

As #96 was for datepicker and was closed I'm opening a new issue.

![image](https://user-images.githubusercontent.com/8679058/127620466-457afd82-1f0b-476e-bc5d-196b6bcafaa5.png)

**Comment by vanpra** [comment]
Buttons are now passed in through the `buttons` parameters of build.

**Comment by Tgo1014** [comment]
@vanpra Thanks!
Shouldn't this breaking change be in the changelog?

**Comment by vanpra** [comment]
It was already in the change log under the 0.5.0 version but I've a bit more emphasise for the breaking changes. Thanks for letting me know!
